/*----------------------------------------------------------------------------
#
#   This file is part of the SIMD Loops project. For more information, visit:
#     https://gitlab.arm.com/architecture/simd-loops
#
#   Copyright (c) 2025, Arm Limited. All rights reserved.
#
#   SPDX-License-Identifier: BSD-3-Clause
#
----------------------------------------------------------------------------*/

// Random json file

#include "helpers.h"

uint8_t sample_json[] =
    "[\n"
    "  -1001124724,\n"
    "  true,\n"
    "  false,\n"
    "  {\n"
    "    \"qwzyoiuost\": false,\n"
    "    \"cjopgnu\": {\n"
    "      \"foalv\": {\n"
    "        \"rlzyv\": false,\n"
    "        \"qprwoggp\": \"4TUcXtlr7uSlaTfFDq\",\n"
    "        \"gfyveu\": {\n"
    "          \"iouaemrwi\": {\n"
    "            \"wpebctgoer\": [\n"
    "              \"H6tAYDl6ykcvMMMvLV\",\n"
    "              [\n"
    "                true,\n"
    "                [\n"
    "                  \"H\",\n"
    "                  true,\n"
    "                  \"PPvsZEiPQ_nxC\",\n"
    "                  true,\n"
    "                  true,\n"
    "                  false,\n"
    "                  false,\n"
    "                  true\n"
    "                ],\n"
    "                \"Eo9l6\",\n"
    "                [\n"
    "                  false,\n"
    "                  \"i\",\n"
    "                  2073204919,\n"
    "                  \"EoWiBHbcPZms3ZB-UB\",\n"
    "                  false,\n"
    "                  \"yt\",\n"
    "                  false\n"
    "                ],\n"
    "                true,\n"
    "                [\n"
    "                  762496935,\n"
    "                  true,\n"
    "                  false,\n"
    "                  \"Pu\",\n"
    "                  true,\n"
    "                  false\n"
    "                ],\n"
    "                {\n"
    "                  \"hnyhletcno\": 637391014.5364603,\n"
    "                  \"bmnrfqvuu\": 1297777655,\n"
    "                  \"ekbnzknhkno\": true,\n"
    "                  \"rhwkxnjy\": \"Y_gegXEjQMsORyS2tVL\"\n"
    "                },\n"
    "                \"9TR9JAzVHrcSN_v\",\n"
    "                \"iMSAXMDrSpOJVe\"\n"
    "              ],\n"
    "              false,\n"
    "              -1728634232,\n"
    "              {\n"
    "                \"nblqeanndgeg\": \"d8zdkYZ5UznQPM\",\n"
    "                \"qndxrdox\": {\n"
    "                  \"vixot\": -732701662.1237628,\n"
    "                  \"tynqyfnm\": -2117872587,\n"
    "                  \"agcqlkkipdf\": false,\n"
    "                  \"dihwc\": true\n"
    "                },\n"
    "                \"utdcqgko\": [\n"
    "                  1310674979,\n"
    "                  true,\n"
    "                  -271417947,\n"
    "                  -1353978037.3672442,\n"
    "                  false,\n"
    "                  true,\n"
    "                  \"L_sOscUS4dCTmznz\"\n"
    "                ],\n"
    "                \"fooaohvmja\": false,\n"
    "                \"jzhxiwpw\": [\n"
    "                  -673891072,\n"
    "                  \"sk3uiOBdRl-s8\",\n"
    "                  false,\n"
    "                  1834401848.5266547\n"
    "                ],\n"
    "                \"lhltj\": \"0ng\"\n"
    "              },\n"
    "              \"j979TkDy-Rgl9hAYRoQ\"\n"
    "            ],\n"
    "            \"bxoeupgvd\": {\n"
    "              \"eeuund\": [\n"
    "                [\n"
    "                  \"zbS7i9SCwAglh\"\n"
    "                ],\n"
    "                [\n"
    "                  \"wkPDisIfvEICXDNW\",\n"
    "                  \"SQD\"\n"
    "                ]\n"
    "              ],\n"
    "              \"oftgzqlemxdp\": 706183952.7886788,\n"
    "              \"mhaxq\": [\n"
    "                {\n"
    "                  \"phxdahancn\": false,\n"
    "                  \"tbxqyajzt\": false,\n"
    "                  \"lldlfvo\": \"NXBvPDFdMO\"\n"
    "                },\n"
    "                165678095.90106773,\n"
    "                true,\n"
    "                {\n"
    "                  \"exyfxbqzgt\": -1426430056.9906638,\n"
    "                  \"jfumygt\": true,\n"
    "                  \"olfpuo\": false,\n"
    "                  \"iohayhadu\": \"Nv\",\n"
    "                  \"exbafop\": -329558125,\n"
    "                  \"onmpwi\": 996035002.9904199\n"
    "                },\n"
    "                true\n"
    "              ],\n"
    "              \"tbdktc\": true,\n"
    "              \"rcxwlbdffek\": \"idSN-5L7gWw\"\n"
    "            },\n"
    "            \"eirqfemwydxd\": [\n"
    "              \"rEYUY72rk681bg5thY-\",\n"
    "              1961069278,\n"
    "              true,\n"
    "              [\n"
    "                [\n"
    "                  true,\n"
    "                  -723260859.1632991,\n"
    "                  -1584627766,\n"
    "                  true\n"
    "                ],\n"
    "                [\n"
    "                  false\n"
    "                ],\n"
    "                \"t\",\n"
    "                [\n"
    "                  false,\n"
    "                  true,\n"
    "                  \"U_6XKKtCIINO3QuI\"\n"
    "                ],\n"
    "                \"0jfAhTZbx\",\n"
    "                {\n"
    "                  \"mggybusbq\": 72847816,\n"
    "                  \"rkdeexho\": false,\n"
    "                  \"cnqipmb\": false,\n"
    "                  \"mjgszqidms\": true,\n"
    "                  \"fjtnwk\": -1195970540.5390375,\n"
    "                  \"jwbwmnoto\": \"lDF-aoUNujI\",\n"
    "                  \"npghsxqnnvcd\": \"sJQ\",\n"
    "                  \"zehpfwomes\": 1970362540\n"
    "                },\n"
    "                [\n"
    "                  true,\n"
    "                  -2079247471,\n"
    "                  \"2rXX3D0RLGoTUKSjfdYj\",\n"
    "                  \"a3GrBm\",\n"
    "                  \"OoCvHleMPJgxnGpt3I\",\n"
    "                  true,\n"
    "                  \"TDEI\",\n"
    "                  true\n"
    "                ],\n"
    "                [\n"
    "                  \"tZuPhAgV\",\n"
    "                  1598020170.370911,\n"
    "                  -1888926202.3359208,\n"
    "                  false,\n"
    "                  1853499837,\n"
    "                  \"6nhki\",\n"
    "                  true,\n"
    "                  -59089807\n"
    "                ],\n"
    "                \"IVvC3_N1afJUf-9Qse\"\n"
    "              ],\n"
    "              [\n"
    "                [\n"
    "                  true,\n"
    "                  \"bXcjdgwOM_yJVrBO\",\n"
    "                  1452861133.6821532\n"
    "                ],\n"
    "                {\n"
    "                  \"xwrjovqeouad\": false,\n"
    "                  \"nmyubaphmief\": -1647272920.5659335,\n"
    "                  \"igyxpinyugbp\": \"kMNNmT0ECM9R\",\n"
    "                  \"vmdugiky\": 1236281844,\n"
    "                  \"ehcidfxkkly\": false,\n"
    "                  \"cnawfggko\": false,\n"
    "                  \"anagf\": false,\n"
    "                  \"yznxjlqolds\": \"upJw7R9a-eQjxql\",\n"
    "                  \"mydltq\": false\n"
    "                },\n"
    "                false\n"
    "              ],\n"
    "              {\n"
    "                \"qxysggo\": true,\n"
    "                \"spzlmygdb\": true,\n"
    "                \"rvxwcahx\": {\n"
    "                  \"xmydgwm\": false,\n"
    "                  \"tkmny\": 699845110,\n"
    "                  \"sxwcbazsfnrp\": \"lyV\",\n"
    "                  \"brdvvx\": 976953398.3203604,\n"
    "                  \"vgqbuzh\": -801214934.3445406,\n"
    "                  \"nyienzx\": false\n"
    "                },\n"
    "                \"appjhzbh\": {\n"
    "                  \"eraxjvznv\": -924101785.3107463,\n"
    "                  \"xnriool\": -1831389543,\n"
    "                  \"pkiorrbtse\": false,\n"
    "                  \"anewrhfm\": \"zjksYKplo05i-2oYf\",\n"
    "                  \"alqmkmg\": false,\n"
    "                  \"xkjlzo\": -620363703.9531119,\n"
    "                  \"oiklrdw\": \"A9_SVvgMkkuS2ipRrhgj\",\n"
    "                  \"ikefmbuk\": \"G_Z7TN\",\n"
    "                  \"oowzedpt\": \"L\"\n"
    "                }\n"
    "              },\n"
    "              false,\n"
    "              [\n"
    "                1649831545,\n"
    "                [\n"
    "                  true,\n"
    "                  1575204926,\n"
    "                  \"DMiXA4Jnaf\",\n"
    "                  \"VnpR0VVogc7UfMwCcxSP\",\n"
    "                  \"lJZ0GLYafzRyq\"\n"
    "                ],\n"
    "                1869324445.6171458,\n"
    "                {\n"
    "                  \"xebzbkvo\": false,\n"
    "                  \"qtssyeewp\": false,\n"
    "                  \"drpgnzprvods\": true,\n"
    "                  \"dgkuyzy\": -564933124,\n"
    "                  \"bcvulse\": \"kLt3g\",\n"
    "                  \"ikzvzrxai\": 630292018\n"
    "                },\n"
    "                [\n"
    "                  -898395704,\n"
    "                  \"C9Vqd_sjpnWIrI\",\n"
    "                  false,\n"
    "                  \"g1-3kwesdt\",\n"
    "                  \"kG57JmZrqrwuOLI4oKA6\"\n"
    "                ]\n"
    "              ],\n"
    "              true\n"
    "            ],\n"
    "            \"wzipyiocbzp\": -583275590,\n"
    "            \"lumxngpen\": true,\n"
    "            \"pfbudtgzn\": true\n"
    "          },\n"
    "          \"tsbnikgd\": true\n"
    "        },\n"
    "        \"rfjzbsid\": 1009720028.8290068,\n"
    "        \"kwzggc\": \"OV29B\",\n"
    "        \"qmumrxkizj\": 825173927,\n"
    "        \"hazrxng\": -505562174\n"
    "      },\n"
    "      \"hzoklncnddp\": \"E9yWpPm0eAA7kXQaQ\",\n"
    "      \"xrzhg\": [\n"
    "        \"f_XpCt6HEFNU\",\n"
    "        \"4NX\"\n"
    "      ],\n"
    "      \"cghdyv\": false,\n"
    "      \"upqqlpn\": false,\n"
    "      \"dvvacycgm\": \"neaAq1rfDZ1Uag-yPUs\",\n"
    "      \"azytvpnvtgw\": \"L-lpeKCVr\",\n"
    "      \"rpjyj\": [\n"
    "        \"etMVB\",\n"
    "        \"0vZ0nzJMZ2t5\",\n"
    "        \"6205N5MQ9H8ZbEb3FseU\",\n"
    "        true,\n"
    "        -1209283405.911274,\n"
    "        \"RwNQPvrESg-Q\",\n"
    "        true\n"
    "      ],\n"
    "      \"mheaxksyyo\": {\n"
    "        \"pbdnlojoxo\": [\n"
    "          \"Xo4T8P1LF2lp6s3HodrS\",\n"
    "          -1979127950.3656504,\n"
    "          false,\n"
    "          [\n"
    "            [\n"
    "              [\n"
    "                -24063525.82313488,\n"
    "                \"BZRBQZ3y0\",\n"
    "                [\n"
    "                  true,\n"
    "                  \"eCGA\",\n"
    "                  \"Kks5TIz_Z\",\n"
    "                  \"F7FmhuXBx9wF\",\n"
    "                  979997284.0240536,\n"
    "                  \"FYG2otI\",\n"
    "                  -1241222881\n"
    "                ]\n"
    "              ],\n"
    "              \"Vg\",\n"
    "              {\n"
    "                \"ndnfqfodtk\": {\n"
    "                  \"pchlvmrv\": -1168309317,\n"
    "                  \"tvrjwezyrf\": false,\n"
    "                  \"tvzwlch\": true\n"
    "                },\n"
    "                \"qjcyoim\": -954533075.2625433,\n"
    "                \"jqnynt\": false,\n"
    "                \"gszqacwu\": \"ZZolhL5ds65V0nE\",\n"
    "                \"olmsgl\": \"lzbseDN8xF\",\n"
    "                \"jnyejcjjtja\": false,\n"
    "                \"wkfaw\": true,\n"
    "                \"qpgfuizzg\": \"4NWYyonrYqRvsQ\",\n"
    "                \"mcnwjq\": {\n"
    "                  \"yezmoweym\": true,\n"
    "                  \"kffrwdpuvpc\": false,\n"
    "                  \"fbszfb\": false,\n"
    "                  \"kpnlo\": \"1dx1LI2ga0X\",\n"
    "                  \"ezqcb\": false,\n"
    "                  \"txdulyqbhbp\": false,\n"
    "                  \"ndloefs\": \"Ppz3x25nc7I\",\n"
    "                  \"upsob\": -1997322793.415587,\n"
    "                  \"fdrgeydbizgz\": false\n"
    "                }\n"
    "              },\n"
    "              true,\n"
    "              \"Eh3sUQ1\",\n"
    "              \"zTFZ7bqK5DMb0F8mRDp\",\n"
    "              {\n"
    "                \"vkrxrsxgjeb\": true,\n"
    "                \"nclxg\": 1491337775,\n"
    "                \"tycse\": \"owtjEW5A\",\n"
    "                \"jyxbppwxi\": -1007617475,\n"
    "                \"iozsk\": -1111769868.6589642,\n"
    "                \"uhbfiqbnm\": [\n"
    "                  \"EMjM0u7o1fttWjNjt\"\n"
    "                ],\n"
    "                \"ujmxlrpmnw\": 1904681476.4928308,\n"
    "                \"mixvwkfkmhsg\": \"XKe\",\n"
    "                \"lhvbmd\": [\n"
    "                  -127288595.66998683,\n"
    "                  \"SvNY0El7rg_x8MS6RiW\",\n"
    "                  \"Sz6_oMBAl\"\n"
    "                ]\n"
    "              }\n"
    "            ],\n"
    "            2022861583,\n"
    "            true,\n"
    "            {\n"
    "              \"gqukbc\": {\n"
    "                \"pvscdrskxr\": \"LDCsefcX4L6-TIDF\",\n"
    "                \"bdbumzeeujw\": {\n"
    "                  \"lkixsahdpp\": -1211015773,\n"
    "                  \"ooewgnbxszm\": \"OJ471LQ\",\n"
    "                  \"joqjgtem\": 414969068,\n"
    "                  \"ovguouyqate\": -1152260430,\n"
    "                  \"rlqvtgy\": \"C4LlAwpdtYeA4\",\n"
    "                  \"ghdrkukwfjy\": 1048526081,\n"
    "                  \"rkfrqmc\": \"whn1Y_ssww\"\n"
    "                },\n"
    "                \"fuqwvheafndt\": \"hcUpuoIUQCn7pOes\",\n"
    "                \"mmmupfikqw\": \"i_v25MbxcsB3jZ\"\n"
    "              }\n"
    "            },\n"
    "            -1369083206.486973\n"
    "          ],\n"
    "          false\n"
    "        ],\n"
    "        \"xbvtljd\": {\n"
    "          \"tdgxlxumhx\": 885082806.9822215,\n"
    "          \"gihvkcak\": [\n"
    "            {\n"
    "              \"mqcaux\": 158199382.11337635,\n"
    "              \"zjnas\": true,\n"
    "              \"elxoehpfy\": \"MwW3EBpnbIAFSO34\",\n"
    "              \"bbzfllixz\": -1853880993.916228,\n"
    "              \"hkmhcyjj\": 1277755866.5091128\n"
    "            },\n"
    "            \"zAVv3extcY3C9WAQvcW\",\n"
    "            [\n"
    "              true,\n"
    "              [\n"
    "                {\n"
    "                  \"yittjdwusox\": 1334642119,\n"
    "                  \"eurjyyf\": \"6r9lXuDmWI-U-FZ9j8\"\n"
    "                }\n"
    "              ],\n"
    "              {\n"
    "                \"youbsyxomxrd\": \"I\",\n"
    "                \"mlhcnuso\": \"ZupoyCns88XUofm5cbe\",\n"
    "                \"fatvm\": \"25WBGt9hqUG5kcQuIUO\",\n"
    "                \"kfiqugledfqf\": {\n"
    "                  \"bvkjvcirbzqs\": false\n"
    "                },\n"
    "                \"ixyexydke\": {\n"
    "                  \"rjtiexndequt\": -325109966.46062505,\n"
    "                  \"vrnyylykvvq\": \"QaFd\",\n"
    "                  \"kalsqbepxjzo\": 772497216,\n"
    "                  \"iwyqt\": false\n"
    "                },\n"
    "                \"wtheufsgfjb\": {\n"
    "                  \"nqjhwx\": \"TNm570\",\n"
    "                  \"jlqrc\": \"gSJ_RQM3gUG\"\n"
    "                },\n"
    "                \"zvwbcxcc\": \"9q8GrnMbY\"\n"
    "              },\n"
    "              [\n"
    "                [\n"
    "                  142798553.74059477\n"
    "                ],\n"
    "                \"0a3hME-ZZ2KDjRY1d\",\n"
    "                false,\n"
    "                true,\n"
    "                \"0a-ypm09IdNNGK9aH\"\n"
    "              ],\n"
    "              [\n"
    "                false,\n"
    "                [\n"
    "                  \"PGTiLFZS6Ir637Vid5W\",\n"
    "                  -887881306.3364472,\n"
    "                  \"N5hLZ0YQbBzKyVgO-\"\n"
    "                ]\n"
    "              ]\n"
    "            ],\n"
    "            [\n"
    "              {\n"
    "                \"aqriymweku\": {\n"
    "                  \"zpypmb\": 1586715049.8615396\n"
    "                },\n"
    "                \"oaszllra\": [\n"
    "                  true,\n"
    "                  \"0CgtwH\",\n"
    "                  true,\n"
    "                  \"oNMuNyIitzetng0a8RUz\",\n"
    "                  false\n"
    "                ],\n"
    "                \"uftosj\": [\n"
    "                  true,\n"
    "                  116256636.67410165,\n"
    "                  true,\n"
    "                  \"lHHufFqX3StawV3_\",\n"
    "                  \"oBdqluzXdbh8ZsTxs4l\",\n"
    "                  \"JZ5DMlprNlFbb\",\n"
    "                  \"PK2l4Ri9uSHU\",\n"
    "                  false,\n"
    "                  104357411.14863656\n"
    "                ],\n"
    "                \"dxwop\": true,\n"
    "                \"mdyfbt\": [\n"
    "                  \"m3WyAHQCnjYek4OrGfiB\",\n"
    "                  true,\n"
    "                  354096773.7692196,\n"
    "                  true\n"
    "                ],\n"
    "                \"wprrkqszoa\": \"uhTi\",\n"
    "                \"xkjsf\": [\n"
    "                  -771101198,\n"
    "                  \"eEKibU\",\n"
    "                  \"tPFG\",\n"
    "                  -958542753,\n"
    "                  1752530948,\n"
    "                  \"34WOUf7goOg5V\",\n"
    "                  1255257367.563467,\n"
    "                  false,\n"
    "                  88558375.87892757\n"
    "                ],\n"
    "                \"hagzwnacgkbp\": [\n"
    "                  \"JZQJGLAfcbv\",\n"
    "                  \"zMs5iIvb\",\n"
    "                  \"JJ\"\n"
    "                ],\n"
    "                \"dljtucdpjtxv\": [\n"
    "                  1167257710.1426883,\n"
    "                  156763639,\n"
    "                  true,\n"
    "                  false,\n"
    "                  \"kT6Nk1hnS\",\n"
    "                  1501716011.867569\n"
    "                ]\n"
    "              }\n"
    "            ],\n"
    "            -1428116912,\n"
    "            {\n"
    "              \"gpvnlzroiab\": [\n"
    "                \"x\",\n"
    "                false,\n"
    "                true,\n"
    "                [\n"
    "                  true,\n"
    "                  1976562176,\n"
    "                  -658101440,\n"
    "                  false,\n"
    "                  false\n"
    "                ],\n"
    "                \"bU\",\n"
    "                -260464306.92516604,\n"
    "                [\n"
    "                  \"35NZmjO\",\n"
    "                  true,\n"
    "                  true\n"
    "                ],\n"
    "                \"SvoVG6qsuO\"\n"
    "              ],\n"
    "              \"ratizdtowa\": \"I1-yoEH2WfHwxR08pmQ\",\n"
    "              \"rsuonq\": [\n"
    "                {\n"
    "                  \"ioeomtd\": true,\n"
    "                  \"onxqhn\": false,\n"
    "                  \"zogbq\": \"KM6uB5GlRk\",\n"
    "                  \"uobvoe\": true,\n"
    "                  \"hxvmogfazk\": -616714139.7765284,\n"
    "                  \"jgcqlue\": true,\n"
    "                  \"qtfwzz\": false\n"
    "                },\n"
    "                false\n"
    "              ],\n"
    "              \"fpnepfoudu\": false,\n"
    "              \"fstqylog\": true\n"
    "            },\n"
    "            false\n"
    "          ],\n"
    "          \"ycmrrqswl\": 1515526160,\n"
    "          \"lalnthgnjj\": [\n"
    "            {\n"
    "              \"emvtjlqlyn\": \"yULP4o0TA3OInYyzD\",\n"
    "              \"tkfwq\": false,\n"
    "              \"pjlesnpxjoeo\": \"bShz4ZC\",\n"
    "              \"sqmslszdqo\": -2026150918,\n"
    "              \"vosympdop\": true\n"
    "            },\n"
    "            false,\n"
    "            {\n"
    "              \"oulan\": [\n"
    "                {\n"
    "                  \"kgzzqhgcyhnk\": \"gesyleSBgDLQLOED\",\n"
    "                  \"aeaqttzrz\": \"pFq08Z\",\n"
    "                  \"spdwayjg\": true\n"
    "                },\n"
    "                false\n"
    "              ],\n"
    "              \"cqclmut\": {\n"
    "                \"ugrzp\": \"OEmRwSHhVKmWITSmo41\",\n"
    "                \"ncmxoybgc\": -1417972334.9294631,\n"
    "                \"bkvxjn\": \"f\",\n"
    "                \"xxbnwpm\": {\n"
    "                  \"xdsozr\": 268274598.19932726\n"
    "                },\n"
    "                \"vbudms\": true,\n"
    "                \"vojmvbfjo\": 1445255767.1483831,\n"
    "                \"jbbnlvrtc\": \"jRKsdJdGmcQ1H\",\n"
    "                \"fccshn\": [\n"
    "                  \"V1-\",\n"
    "                  191504821.68991783,\n"
    "                  1743963554,\n"
    "                  false,\n"
    "                  -1090005652.8108737,\n"
    "                  914442975,\n"
    "                  false,\n"
    "                  \"9a7U7zA0qe74u\",\n"
    "                  -1686744869.7010558\n"
    "                ]\n"
    "              },\n"
    "              \"gbracjvg\": true,\n"
    "              \"zyaejf\": [\n"
    "                1606780027\n"
    "              ],\n"
    "              \"ohmxgfrumriw\": \"2Ul8L5Aqpz\",\n"
    "              \"obksjpjxnphj\": -879564996,\n"
    "              \"jjutstanjday\": false,\n"
    "              \"utlcazd\": -625502418\n"
    "            },\n"
    "            -1662602719,\n"
    "            {\n"
    "              \"yfvtqyj\": {\n"
    "                \"iaggcrsojn\": -404926688,\n"
    "                \"hwisesbptr\": [\n"
    "                  358086513,\n"
    "                  true,\n"
    "                  false,\n"
    "                  \"1OZbwanID0\",\n"
    "                  1545388759,\n"
    "                  -1141034823,\n"
    "                  926130636\n"
    "                ],\n"
    "                \"ajcnsazgewku\": [\n"
    "                  995931265.2501994,\n"
    "                  true,\n"
    "                  -589990541.783768,\n"
    "                  true,\n"
    "                  -466923181.83344597,\n"
    "                  \"Zp7GiV-WdQ\",\n"
    "                  true,\n"
    "                  \"Rjwq9DQANDnIkNub3\",\n"
    "                  false\n"
    "                ],\n"
    "                \"iclhyxqju\": \"tDI7bW4nkOJa\",\n"
    "                \"kdqlqo\": \"TlQvnvHW5e9f\"\n"
    "              },\n"
    "              \"zhxcgie\": [\n"
    "                [\n"
    "                  -1642307471,\n"
    "                  \"J4ew3wVTcaq5J7H0M\",\n"
    "                  \"HtpqwDvWb\"\n"
    "                ],\n"
    "                {\n"
    "                  \"covyhmnfym\": \"NjRW2rBFDj\",\n"
    "                  \"gihire\": true\n"
    "                },\n"
    "                false,\n"
    "                [\n"
    "                  -525851572.46017414,\n"
    "                  false,\n"
    "                  false,\n"
    "                  -538826236.2611501\n"
    "                ]\n"
    "              ],\n"
    "              \"mkmrgivm\": [\n"
    "                \"RO9gjkq\",\n"
    "                \"9cqMLsLNvj3\"\n"
    "              ]\n"
    "            }\n"
    "          ],\n"
    "          \"iemrjh\": \"0WVn1N\",\n"
    "          \"uywircvufgw\": false,\n"
    "          \"vzwcnw\": \"WnbovSXaMzb-eyVlLnX\",\n"
    "          \"chmfhaju\": {\n"
    "            \"wmnmsf\": true\n"
    "          }\n"
    "        },\n"
    "        \"bxnaymqt\": false,\n"
    "        \"pjdwnl\": \"SzmRZa_Hq\",\n"
    "        \"ettpuijywg\": {\n"
    "          \"aswyyuais\": true,\n"
    "          \"uzkafecbp\": \"VZtmlngc9GqXbyqp2B2k\",\n"
    "          \"qcdspiqpzwp\": [\n"
    "            [\n"
    "              1946791168,\n"
    "              \"S15Eh9d0gNrxE\",\n"
    "              false\n"
    "            ],\n"
    "            false,\n"
    "            true,\n"
    "            -2057045822.726386\n"
    "          ],\n"
    "          \"eajoz\": 759928182.1392952,\n"
    "          \"mvhlqejgjeq\": \"o1Hwm8mvfnhE6M\",\n"
    "          \"oosjbzowynh\": [\n"
    "            \"HRANsAjzuRqa6CVa\",\n"
    "            \"RvkG_tharES6gsg06nn\",\n"
    "            \"1j8IgxlBrZ6lgDT50UF\",\n"
    "            1832583094.8721294,\n"
    "            false,\n"
    "            false,\n"
    "            false\n"
    "          ]\n"
    "        },\n"
    "        \"zuyqvi\": -693833060,\n"
    "        \"phudh\": false,\n"
    "        \"mgnxig\": \"KG-1gEWmpHm3RxZ\",\n"
    "        \"lwtdk\": \"V96l7\"\n"
    "      }\n"
    "    },\n"
    "    \"rgffyu\": true,\n"
    "    \"tobqt\": \"coVkh4fkUqkzXh\",\n"
    "    \"hzyfwcvfparh\": -1280918744.2374861,\n"
    "    \"qjjzeyhkfcan\": {\n"
    "      \"ehgkjmhgthyy\": {\n"
    "        \"byentf\": 89335836,\n"
    "        \"ajexihh\": \"tfIPqbxi\",\n"
    "        \"qzgseleq\": \"hC4VipCx5a\",\n"
    "        \"wcykzummb\": false,\n"
    "        \"ibllwakgbar\": true\n"
    "      }\n"
    "    },\n"
    "    \"dtqbfdi\": 482559477\n"
    "  }\n"
    "]";

uint32_t sample_json_size = sizeof(sample_json);
